### ISSUE TITLE
Correct Docker-Compose

### ISSUE THREAD

**Issue by iandday** [danielbrendel/hortusfox-web#101]
There is an incorrect database variable in the docker-compose file

**Comment by gonsalvesc** [comment]
I would also suggest pointing MariaDB to version 10.11

**Comment by danielbrendel** [comment]
> I would also suggest pointing MariaDB to version 10.11

Do you still have an error log that indicates why it does not work with a prior MariaDB version?

**Comment by danielbrendel** [comment]
Closing this as resolved. If there is a major issue with different versions of mariadb we'd need a separate issue with detailed error info.
