### ISSUE TITLE
Email only supports SMTPS or TLS encryption

### ISSUE THREAD

**Issue by iandday** [danielbrendel/hortusfox-web#103]
I utilize an internal mail relay for all my self-hosted tools to reduce credential exposure and credential reset work.  Hortusfox does not support sending unencrypted mail.  Allowing unencrypted email will enable the use of internal mail relays.

**Comment by danielbrendel** [comment]
@iandday does it work now if you try from main branch? In admin settings under Mail you can now specify encryption "none" which will disable encrypted e-mail and force-disable auto tls.

**Comment by iandday** [comment]
yes this works, thank you!

**Comment by danielbrendel** [comment]
Resolved.
