### ISSUE TITLE
Encryption type SSL for mail throws an error

### ISSUE THREAD

**Issue by roland-d** [danielbrendel/hortusfox-web#116]
I have installed Hortusfox via Docker and it runs fine. When I set the encryption type to SSL and I create a user I get the error `Unknown encryption type: ssl`
![image](https://github.com/danielbrendel/hortusfox-web/assets/359377/56958ae3-f4b1-4bba-8ad6-db63bc18239c)

If I set the encryption type to TLS and port to 587, this works for me but just wanted to share what I ran into. If it is related to my setup, feel free to close this as not an issue :)

**Comment by danielbrendel** [comment]
Hi, thanks for your feedback!

Which version do you use?

**Comment by roland-d** [comment]
Hello Daniel,

Apologies I should have mentioned that of course.
```
HortusFox v2.1
PHP Version: 8.2.0
MySQL Version: 11.2.3-MariaDB-1:11.2.3+maria~ubu2204
```
