### ISSUE TITLE
Database is reset on every docker down and up

### ISSUE THREAD

**Issue by roland-d** [danielbrendel/hortusfox-web#117]
Hello Daniel,

Thank you for making HortusFox available on Docker. After some struggles I have it now running fine except for when I bring down the service and up again. This results in the database being reinitialized.

Now I have seen issue #65 and #82 but my database still gets wiped. Looking at the code I guess it is because of both migrations (up and down) having a `->drop()` statement in them.

Is there any way to prevent the database from being dropped when I stop and start the containers?

This is the log of the app container when it starts up:
```
app-1  | Database is available.
app-1  | Running unapplied database migrations...
app-1  | Creating "AppModel_Migration"
app-1  | Creating "CacheModel_Migration"
app-1  | Creating "ChatMsgModel_Migration"
app-1  | Creating "ChatViewModel_Migration"
app-1  | Creating "InvGroupModel_Migration"
app-1  | Creating "InventoryModel_Migration"
app-1  | Creating "LocationsModel_Migration"
app-1  | Creating "LogModel_Migration"
app-1  | Creating "PlantPhotoModel_Migration"
app-1  | Creating "PlantsModel_Migration"
app-1  | Creating "TaskInformerModel_Migration"
app-1  | Creating "TasksModel_Migration"
app-1  | Creating "UserModel_Migration"
app-1  | Creating "VersionModel_Migration"
app-1  | The database has been listly migrated!
app-1  | App settings profile does not exist. Creating...
app-1  | App settings profile created.
app-1  | Admin user (rolandd+hortusfox@rolandd.com) does not exist. Creating...
app-1  | Admin user created. 
app-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.30.0.4. Set the 'ServerName' directive globally to suppress this message
app-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.30.0.4. Set the 'ServerName' directive globally to suppress this message
app-1  | [Sat Feb 17 18:21:30.625027 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.2.0 configured -- resuming normal operations
app-1  | [Sat Feb 17 18:21:30.625055 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by Millio345** [comment]
Just to make sure I'm experiencing the same issue: When I stop , remove and recreate the container the whole database is reset (and all plants are removed) , even when there should be no updates / migrations to perform? 

Seems like a pretty huge problem if that's the case :/

**Comment by roland-d** [comment]
@Millio345 That is exactly my issue, that is why I make sure to make a database backup before updating HortusFox and after the update restore the database.

**Comment by danielbrendel** [comment]
Yes, the problem here is when the app container is deleted, then the migration list file gets also deleted. This is basically the source file to determine which migrations are changed and which are not. When the list file is lost, then all tables get recreated.

**Comment by Millio345** [comment]
> Yes, the problem here is when the app container is deleted, then the migration list file gets also deleted. This is basically the source file to determine which migrations are changed and which are not. When the list file is lost, then all tables get recreated.

Thank you for the clarification; For now I have solved this locally by adding /var/www/html/app/migrations/migrations.list to the volume mounts so I can at least use it for now without losing everything every time the container is removed.

**Comment by danielbrendel** [comment]
It should work now. Can you confirm this on your end?

**Comment by roland-d** [comment]
@danielbrendel Thank you for the fix, I will test this over the weekend.

**Comment by roland-d** [comment]
@danielbrendel I have just tested these changes and they work for me as well. Thanks.

**Comment by danielbrendel** [comment]
Closed as resolved.
