### ISSUE TITLE
Please tag docker images with the versions they are built for

### ISSUE THREAD

**Issue by boc-the-git** [danielbrendel/hortusfox-web#123]
Hopefully the title is self explanatory. Rather than only having "latest", you can build an archive of images with specific version tags.

**Comment by danielbrendel** [comment]
Hi, that's actually good, I'll merge this prior to the next version release!

**Comment by boc-the-git** [comment]
PR is merged, and working. https://github.com/users/danielbrendel/packages/container/hortusfox-web/187230990?tag=v2.3
