### ISSUE TITLE
Locations not included in backup

### ISSUE THREAD

**Issue by Samurai1201** [danielbrendel/hortusfox-web#126]
Hi Daniel,
first of all thank you for the amazing project! I am really enjoying it, keep up the great work!

Unfortunately right now I have an issue with the db getting reset with every redeploy of the docker container (I know you're working on it). So I was trying to bypass this problem by creating regular backups. I then found out that these do not contain the locations I created in the admin panel. I have 15 of them, so recreating them is quite a task. 

Could you please include the locations in the backups that can be manually created in the admin panel? 

Thank you for looking into this!

**Comment by danielbrendel** [comment]
Hi, glad you like it. I'll include the locations in the backup. Regarding the db reset: This will be handled here: https://github.com/danielbrendel/hortusfox-web/issues/117
