### ISSUE TITLE
Add users locally

### ISSUE THREAD

**Issue by chuckygoodguy** [danielbrendel/hortusfox-web#137]
Hello,
Is there a way to add users locally without having to send email?
My instance is not forward facing local access only. So far this has been wonderful software, but adding users needs to be easier.

Thanks

**Comment by danielbrendel** [comment]
Hi, thank you for your feedback! 

You're right, sending a confirmation e-mail shouldn't be forced. I'll add an update, so that admins can decide whether to send an e-mail or not.
