### ISSUE TITLE
Plants with no location error

### ISSUE THREAD

**Issue by SmileyDrag0n** [danielbrendel/hortusfox-web#138]
On fresh docker installation, when adding a new plant without specifying its location (because there are no locations created yet), I get this message:
`{"code":200,"message":null}`
The plant does not add to the list.

Same thing happens when deleting the only location in the list with nowhere to move existing plants

**Comment by danielbrendel** [comment]
Hi, thanks for the feedback! 
Plants should always belong to a location, so I'll implement a user feedback if there are no locations created yet. Also I'll add that deleting the only location will be refused until an admin created a new location were to move the plants.

**Comment by danielbrendel** [comment]
Resolved.
