### ISSUE TITLE
Raspberry Pi/ARM Docker image

### ISSUE THREAD

**Issue by theh0ff** [danielbrendel/hortusfox-web#141]
Feature Request

Hi, would it be possible to build an ARM docker image for hortusfox-web so that it can run on a Raspberry Pi device?

**Comment by carlossgv** [comment]
+1 here, would love to have HortusFox it in my arm64 server.

**Comment by danielbrendel** [comment]
I agree, this is very useful. I did a quick search and it should be easy
with buildx:

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

I think this will be added to the v2.5 milestone.

Carlos González Villafañe ***@***.***> schrieb am Mo., 25.
März 2024, 21:34:

**Comment by danielbrendel** [comment]
I agree, this is very useful. I did a quick search and it should be easy
with buildx:

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

I think this will be added to the v2.5 milestone.

**Comment by danielbrendel** [comment]
Buildx command:
```
docker buildx build . --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag ghcr.io/danielbrendel/hortusfox-web:latest --push
```

More infos: https://docs.docker.com/build/drivers/docker-container/

Todo: Create workflow to build and push multi-platform image.
Hint: Local tests use this command:
```
docker buildx build . --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag ghcr.io/danielbrendel/hortusfox-web:latest --load
```
However for local testing only one platform can be specified due to current limitations to docker exporter (see https://github.com/docker/buildx/issues/59#issuecomment-616061869)

**Comment by danielbrendel** [comment]
@theh0ff @carlossgv  I just published a build tagged as "beta" that also supports ARM64 images. Would be nice if you could test this and post here whether this works for you or not.

**Comment by danielbrendel** [comment]
That's great! I let this issue open for a while, but if nothing errorneous occurs until the milestone due date, I'll close that issue then.

**Comment by carlossgv** [comment]
Working here too!

<img width="774" alt="image" src="https://github.com/danielbrendel/hortusfox-web/assets/35035810/012a9c09-5d3c-42b8-83df-0eab5819f467">

Running on ARM Oracle server:
uname -a
`Linux ubuntu-server 6.5.0-1019-oracle #19~22.04.1-Ubuntu SMP Tue Mar 12 23:02:13 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by danielbrendel** [comment]
Great! 😊

**Comment by danielbrendel** [comment]
Resolved.
