### ISSUE TITLE
[Feature Request] Remove humidity as mandatory input

### ISSUE THREAD

**Issue by HerrTim** [danielbrendel/hortusfox-web#142]
Hello @danielbrendel,
do you think it's possible to remove the humidity as a mandatory input while adding new plants?
I'm no gardening pro, but for garden plants, the humidity is unnecessary.

Thanks and best regards!

**Comment by danielbrendel** [comment]
I'd made it so now that you don't have to specify humidity, perennial and light level on adding plant. These were made mandatory back in the day when only my gf used the app.
