### ISSUE TITLE
[Feature request] Ability to duplicate plant with its main picture

### ISSUE THREAD

**Issue by tomduud** [danielbrendel/hortusfox-web#153]
It would be great if you could clone one plant to new plants. E.g. if you sow 10 seeds or clones from the mother plant it would be great just duplicate the current plant and its details (like scientific name, main photo) but maybe not with its history.

**Comment by danielbrendel** [comment]
To-do: Duplicate the photo, too, or else it is lost for all plants if just the link to the photo is copied and one of the clones gets deleted.
