### ISSUE TITLE
[Feature request] Show plant id after name in lists

### ISSUE THREAD

**Issue by tomduud** [danielbrendel/hortusfox-web#154]
It would be great to see plant ID number after the name of the plant so you could identify the right plants if you have multiple ones under same name. Optionally it would be nice to see tags as weel if they can be fitted in.

**Comment by tomduud** [comment]
Maybe even possibility to show scientific name (maybe these can be configurable option on the settings).

**Comment by tomduud** [comment]
![plant-id](https://github.com/danielbrendel/hortusfox-web/assets/121978445/cd80d59f-0bb6-4971-8d5f-cc9d0758b7f1)
I did modify the plants.php on my installation to add ID. Not sure abou the color of the badge :) but this help me meanwhile I wait possible proper solution.

**Comment by danielbrendel** [comment]
Will be worked together in this issue: https://github.com/danielbrendel/hortusfox-web/issues/153

**Comment by tomduud** [comment]
Did this feature come with 3.0? I upgraded to 3.0 but I can't find to way show id's with plant on lists / main page and due the upgrade my local changes are now gone :).

**Comment by danielbrendel** [comment]
Is this how you wanted it? Or do you generally want the ID to be shown?

**Comment by tomduud** [comment]
I meant generally showing id with plant name, so it is possible to identify plant if there is multiple ones under same name (e.g. 10 jalapenos). I edited plants.php, profile.php and index.php in /var/www/html/app/views directory to achieve this. Its not fancy but it works, though I need to patch every new release manually.

![plantid](https://github.com/danielbrendel/hortusfox-web/assets/121978445/a3215e7b-446f-499c-b247-26b69c80c326)

**Comment by danielbrendel** [comment]
My apologies, this was a misunderstanding then. I'll reopen this issue.

**Comment by danielbrendel** [comment]
To-do: Show plant ID before the plant name like in the screenshot above. Toggle showing plant IDs via personal preferences, so users can decide how they want it for themselves.

**Comment by danielbrendel** [comment]
@tomduud can you check it out from the main branch in a testing environment? You'd have to enable this feature in your user preferences.

**Comment by danielbrendel** [comment]
Resolved as completed.

**Comment by tomduud** [comment]
Thank you for the update on this issue. Works nicely. Small request though, could also add this to "Last added plants" view on the front page.
