### ISSUE TITLE
[Feature Request] Harvest data logging and reporting

### ISSUE THREAD

**Issue by tomduud** [danielbrendel/hortusfox-web#155]
I know this system is focused on indoor plants, not vegetable gardening, but it would be great if you could log the harvest of the plant and the system calculates the total amount of the harvest for each plant and maybe even combine similar plants totals(maybe tags can be used for this). I think this system could be also used to calculate how many seeds/cuttings one plant produces if one wants to log that information too.

**Comment by danielbrendel** [comment]
I decided not to include this, because, as you said, this system is primarly focused on indoor plants and plant parenting. The problem is it is kinda hard to maintain a perfect balance between these two different use cases. Sorry for the inconveniences.
