### ISSUE TITLE
[Feature Request] History log under the plant

### ISSUE THREAD

**Issue by tomduud** [danielbrendel/hortusfox-web#156]
Is there a way to get history data under the plant. E.g. show when it was repotted, what is the watering schedule in the past etc? Now I see the history data on the front page but not on individual plants.

**Comment by danielbrendel** [comment]
Currently the history log is only shown in the dashboard or in the user profile. But this is a good idea indeed. Maybe even a bit more appealing than just a log.

**Comment by tomduud** [comment]
"more appealing" is a good idea. Maybe show somekind icons related to the log event. E.g. watering, repotting etc. And maybe there is a way to add text items specific to that log also. E.g. I want to mention that watering included this time EC 0.4 of brand X or Y fertilizer instead of just the water.  Also possibility just log one free text (maybe with icon/media if that is the way to go) and keep note field as "overall note for the plant" would be great.

**Comment by danielbrendel** [comment]
To-do: Pagination

**Comment by danielbrendel** [comment]
Resolved.
