### ISSUE TITLE
[Feature Request] Composite table with sortable data

### ISSUE THREAD

**Issue by mikansontap123** [danielbrendel/hortusfox-web#158]
Let me first say thanks for this app, there are so few other self-hosted plant management projects, and this one already has a lot of great features in it. I'm following it very closely. 

My feature request: A page that displays all your plants for a given location or tag in a table/graph format. The table would allow you to sort by some of the key statistics that already exist in the app (e.g. 'Last watered', 'last fertilized', etc.) I realize you can already sort your plant list by these metrics, however the actual data itself is not shown in the list. A table or graph would present a good overview of these metrics for all your plants.

Background: Currently I'm managing all my plants in Google Sheets, where I'm able to see the last watered date for all my plants in a single sheet. I do not water on a schedule, but still find it important to know how long it has been since a particular plant was last watered. This screenshot might give you a better idea:

![image](https://github.com/danielbrendel/hortusfox-web/assets/104760418/ae92ed13-bbcd-4227-a577-9f6613b68a54)

Bonus request: In addition to the already existing "Last watered date" metric, a "Days since last watered" metric would also be helpful.

**Comment by danielbrendel** [comment]
Hi, glad you like the project. 

We can definitely show the actual sorting types value in the plant list view. 

I'll investigate into this further.
