### ISSUE TITLE
Ability to edit fields

### ISSUE THREAD

**Issue by lockheed** [danielbrendel/hortusfox-web#188]
**Description of your request**
The default fields may not be useful to some plant keepers and they'd like to replace them with their own.

**Describe the solution you'd like**
Make fields editable in terms of names, quantity and type (date, text, etc)

![image](https://github.com/danielbrendel/hortusfox-web/assets/3472480/89aeb333-e823-4765-9e09-46664e2fe23f)

**Comment by lockheed** [comment]
Hello @danielbrendel I see you have taken a note of that idea. Can you comment if/when would you expect it to be introduced?

**Comment by danielbrendel** [comment]
@lockheed I just implemented it now.

**Comment by lockheed** [comment]
Fantastic! When will 3.1 be released?

**Comment by danielbrendel** [comment]
It is planned for the end of this month. Probably May, 30th.

I'll close this issue as completed for now.

**Comment by lockheed** [comment]
@danielbrendel I just installed 3.1 but I can't find where can  I edit available fields. In the settings, I can only find option to disable some of the fields.

**Comment by danielbrendel** [comment]
You can't edit the default fields. You can add new fields via the link `Add custom attribute` down below the attribute table in a plants detail page. There you can add what you want for this particular plant. You can also edit and remove attributes again.

**Comment by lockheed** [comment]
Ah, I see now. But it would be great to make those custom attributes stick when creating new plants (like a default templates) because if I have to add 6-9 same new attributes for each plant (because that's my system), that is suboptimal.

**Comment by danielbrendel** [comment]
That's true, this would be even better. Me and my gf don't have that use case, so I wasn't aware of that. This will now be implemented via #208

**Comment by lockheed** [comment]
That's great. Thanks for being so responsive.
