### ISSUE TITLE
Upload images directly from camera

### ISSUE THREAD

**Issue by felixjulianheitmann** [danielbrendel/hortusfox-web#189]
**Description of your request**
When trying to upload an image for a plant, I would like to directly upload from camera. I am mostly using this app from mobile and having to take the photo separately and then uploading is more work, than it needs to be.

![image](https://github.com/danielbrendel/hortusfox-web/assets/75343504/c428503e-ff65-4d97-b810-cee124429924)

**Describe the solution you'd like**
The following code section forms the file dialog:
https://github.com/danielbrendel/hortusfox-web/blob/61bfb1dfd449707ba9c4911c7a0a82abdfb1641e/app/views/layout.php#L545

Updating this with the `accept="image/*"` attribute will trigger mobile devices to display a prompt where you can select between a file picker/media selector and the camera.
On desktop it usually just opens the file picker.

**Additional context**
![image](https://github.com/danielbrendel/hortusfox-web/assets/75343504/f66c7872-d57f-450d-a384-4365f8dc16ca)

This is what it looks like on my phone, after the change.

I have the changes available in a fork which I used for testing.
https://github.com/felixjulianheitmann/hortusfox-web/tree/camera-upload-picker

**Comment by danielbrendel** [comment]
Hi, thank you for that report. I'll check that out. There are some various locations where this needs to be updated.
