### ISSUE TITLE
Upgrade to PHP 8.3

### ISSUE THREAD

**Issue by danielbrendel** [danielbrendel/hortusfox-web#200]
Upgrade product to PHP 8.3.

**Comment by brianw777** [comment]
I tried to downgrade to php8.2 but I get the following error immediately without any of the database created. At least with php8.3 there were many create lines shown then failed on the ChatMsgModel. 

> php asatru migrate:fresh
> PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/html/hortusfox-web-main/vendor/danielbrendel/asatru-php-framework/src/database.php:1198
> Stack trace:
> #0 /var/www/html/hortusfox-web-main/vendor/danielbrendel/asatru-php-framework/src/database.php(1198): PDO->__construct()
> #1 /var/www/html/hortusfox-web-main/asatru(49): require_once('...')
> #2 {main}
>   thrown in /var/www/html/hortusfox-web-main/vendor/danielbrendel/asatru-php-framework/src/database.php on line 1198

> PHP version:
> php -v
> PHP 8.2.20 (cli) (built: Jun  6 2024 16:56:27) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.2.20, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.20, Copyright (c), by Zend Technologies
>

**Comment by danielbrendel** [comment]
Hi,

the error `could not find driver` indicates that the `pdo_mysql` driver is
not enabled.
Can you check whether you have it enabled or not?

Regarding the MySQL syntax error: This seems to be a version/derivative
specific problem. You might want to share your altered docker files, so I
can try to reproduce it on my end.

Kind regards

**Comment by brianw777** [comment]
Thank you for the reply.

I will check the pdo_mysql thing and give php8.2 a try but it may be that my testing system won't work on php8.2 now. Every time I try to install any php related things like composer or php-fpm it always installs the php8.3. I will have another look later. I did find some articles on this issue so I can have a look.

As for the php8.3 mysql syntax error this is not a docker install it is a manual install as per the github main page. I may have to wait for the upgrade to v3.2 if php8.3 is going to be implemented and have another look at it. Or I may just take my server machine and reinstall the OS and start from scratch (it is a new server I am setting up so won't be too much trouble).

Thanks again for the quick reply

**Comment by brianw777** [comment]
So I was looking into this a little more and started searching the database models to see if I could find why it would fail on that specific data creation.  What I found was that there may be an error in the ChatMsgModel.php file. I searched for the line causing the issue "system BOOLEAN NOT NULL DEFAULT 0" but I shortened it to just "system BOOLEAN" to see if any other files had that and the results were:

> grep -ri "system BOOLEAN" *
> app/migrations/AppModel.php:        $this->database->add('chat_system BOOLEAN NOT NULL DEFAULT 1');
> app/migrations/ChatMsgModel.php:        $this->database->add('system BOOLEAN NOT NULL DEFAULT 0');

I assumed the word "system" was the problem so changed it to "chat_system":

> grep -ri "system BOOLEAN" *
> app/migrations/AppModel.php:        $this->database->add('chat_system BOOLEAN NOT NULL DEFAULT 1');
> app/migrations/ChatMsgModel.php:        $this->database->add('chat_system BOOLEAN NOT NULL DEFAULT 0');

After the change in the file app/migrations/ChatMsgModel.ph the database migration went through without any errors.

I haven't went any further yet it is late so I will see if I can get it going when I have some more time.

If my change is incorrect please let me know whenever you get a chance, thanks.

Regards,
Brian

**Comment by danielbrendel** [comment]
Seems to be that `system` is treated as a reserved word:
https://dev.mysql.com/doc/refman/8.4/en/keywords.html#keywords-8-4-detailed-S

I will add a fix for that. Until that you would need to change every
reference to that in the code.

Sorry for the inconvenience!

**Comment by brianw777** [comment]
Thanks. I was thinking it had become a reserved word and I would need to search for every reference and change it. I got thinking after I posted it was probably that reason. The only reason I didn't get any errors during the DB migration was because I changed that instance to a non reserved word but it wouldn't work because all the other references would still be the word "system".

Thanks for confirming that for me.

Regards,
Brian

**Comment by brianw777** [comment]
So just to let you know I made the changes in the code and was able to continue on with the installation. Once I figured out how to change the server from localhost to the ip address of the headless server I am testing on I created a user and was able to log in. I haven't went any farther yet but I was able to log in.

Thanks for all your help.

Regards,
Brian

**Comment by danielbrendel** [comment]
That's great! At this point it should most likely work without further
problems. Setup is the hardest part. 😅
The new version will be released next month and will include the fix as
well.
