### ISSUE TITLE
'Select' button

### ISSUE THREAD

**Issue by Javolixier** [danielbrendel/hortusfox-web#204]
Addition of a button to select plants to apply watering, repotting etc to.

Best case implementation could be a 'select' option, eg user is in a location, hits select, then taps plants to add them to selection, then hits 'water' to change the last watered date to current time.

Can use existing 'set all to x' buttons in conjunction with select.

**Comment by danielbrendel** [comment]
Hi, that's indeed a good suggestion, I'll include this in the next milestone.

**Comment by danielbrendel** [comment]
Implemented via the following commits:

009990241acbf2e7efabafdc0804eb1fa12044d9
ce297903fee1f2cb3c00a998d32928f457a41d12
10734cefb1bfa5bd1a372c6b239597e27b977ccf

To-do: Implement translations of changes of phrases to other languages.
