### ISSUE TITLE
Search filter checkboxes don't seem to apply

### ISSUE THREAD

**Issue by averymd** [danielbrendel/hortusfox-web#206]
I have another one that might be user error. :-) When I perform a search that I'd like to be only tag-based, the submitted search returns with all boxes checked and results include plants with matches in fields other than tags.

**To Reproduce**
1. Have a plant with a tag "av", another plant with "av" in the name (e.g., "agave"), and a third plant with "av" in the scientific name
2. Go to the search page
3. Enter "av" and uncheck "include names", "include scientific names", and "include notes" (leave only "include tags")
4. Click "search"
5. When the page reloads, all three "av" items will show in the results instead of just the one tagged

**Expected behavior**
I expected the results to be filtered to match my checkbox choices. I do see `search_tags` in the POST payload.

**Software:**
- HortusFox version: v3.0
- PHP Version: 8.2.0
- MySQL version: 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
- Docker version: 26.1.2
- Docker compose version: v2.27.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.65.130

**Comment by danielbrendel** [comment]
Hi, thank you for reporting this issue. I can reproduce this and it will be included within the next milestone. :)
