### ISSUE TITLE
Global custom plant attributes

### ISSUE THREAD

**Issue by danielbrendel** [danielbrendel/hortusfox-web#208]
Let users define global plant attributes in admin dashboard that are available to all plants. Add this to the admin section `attributes`.

**Comment by danielbrendel** [comment]
Implementation via b3237e9c75e85cc3a480e481b92fc7f13d585ae2

**Comment by danielbrendel** [comment]
Resolved.

**Comment by qrlt** [comment]
> Implementation via [b3237e9](https://github.com/danielbrendel/hortusfox-web/commit/b3237e9c75e85cc3a480e481b92fc7f13d585ae2)

Current implementation is not global but per plant. Creating global attributes from attributes admin section is not available.

**Comment by danielbrendel** [comment]
> > Implementation via [b3237e9](https://github.com/danielbrendel/hortusfox-web/commit/b3237e9c75e85cc3a480e481b92fc7f13d585ae2)
> 
> Current implementation is not global but per plant. Creating global attributes from attributes admin section is not available.

No, that's wrong. You can create global custom plant attributes from the admin attributes section. However version 3.2 is not released yet. If you want to use this feature now, you'd have to pull from main branch and build the docker image yourself.
