### ISSUE TITLE
Export data to open standard?

### ISSUE THREAD

**Issue by lockheed** [danielbrendel/hortusfox-web#210]
I wanted to see if there is a plan  for an export function. Say, in the future I might want to move my plant data to google sheets, or some other program.  There is a backup function, but looking at the files, it would be quite a bit of  manual labour to extract the data from it into something else.

Can you introduce such function? CSV format or something else, but one that can be imported (including photos) to, for example, Google Sheets or a database.

**Comment by danielbrendel** [comment]
The JSON data could be put in CSV format. For the images I guess you would need to perform some base64 encoding to put them in printable characters and put that encoded text in a column. I don't know if Google Sheets would show them tho, so you would not have viewable images unless you convert them back again.

Do you want to alter them later in Google Sheets? If not then you could just backup the exported zip file to a hosting space.

**Comment by danielbrendel** [comment]
Closed due to inactivity.
