### ISSUE TITLE
Ability to recover and delete plant from History

### ISSUE THREAD

**Issue by Appoxo** [danielbrendel/hortusfox-web#214]
**Description of your request**
Sometimes it happens that a user (me) happens to miss click a button and sends a plant to the graveyard. But either it shouldn't be, or maybe it got revived somehow. Instead of starting anew we could resume from where we started.

**Describe the solution you'd like**
A button to recover it from the graveyard back to the former room or something like a renewed onboarding

**Comment by danielbrendel** [comment]
Hi,

You can already restore a plant from history or delete it via the history
section.

There is a three dotted icon in the top right of a plant card. Admittedly
it can sometimes be a bit invisible depending on the contrast.

More info here: https://hortusfox.github.io/history.html

Hope this helps!

**Comment by Appoxo** [comment]
Omg I am so sorry for bothering.
I looked at the youtube tutorial and was wondering why it was removed.

The issue simply was, that my picture was too bright 😅
![grafik](https://github.com/danielbrendel/hortusfox-web/assets/17850993/31773358-8f8a-4080-b524-91ddc6088189)
