### ISSUE TITLE
Adding an apostrophe to the scientific name makes the item not editable

### ISSUE THREAD

**Issue by Appoxo** [danielbrendel/hortusfox-web#215]
**Describe the bug**
If you use the the apostrophe `'` (for example `Picea glauca 'Hb07' PBR`) makes the item not able to be edited.

**To Reproduce**

1. Create a plant
2. Fill in the scientific name with an apostrophe (Unicode 0x27 to be specific) and save it
3. Try to click the Edit button

**Expected behavior**
It should be able to open the item.

**Screenshots**
![grafik](https://github.com/danielbrendel/hortusfox-web/assets/17850993/0ae592e0-f9ca-4585-aea6-6ee74172125e)

**Software:**
PHP Version: 8.2.0
MySQL Version: 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Server: Linux #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1~bpo11+1 (2024-02-15) auf x86_64
Zeitzone: 2024-05-25 23:09 (Europe/Berlin)
Client: Docker Engine - Community
 Version:    26.1.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox and Chrome
 - Version: FF=126.0, Chrome=125.0.6422.77 (Offizieller Build) (64-Bit)

**Additional context**

**Comment by danielbrendel** [comment]
Hi,

Thank you for the report.

I already fixed this via #207

If you want you can test this via pulling from the main branch in a testing
environment.

The fix will be rolled out via the next version 3.2 (no due date yet).

Kind Regards

**Comment by Appoxo** [comment]
Any way I can test it in the container?  
If not, I'm fine with testing it in 3.2 👍

**Comment by danielbrendel** [comment]
Yes, but you'd have to build the image yourself:

docker buildx build . --platform linux/amd64 --tag
ghcr.io/danielbrendel/hortusfox-web:latest --load
docker-compose up -d

**Comment by Appoxo** [comment]
Don't feel comfortable right now with building/compiling my own stuff atm.
I will take a look once 3.2 has your seal of approval and I'll wait patiently :)

Thanks for making the service.
Helped me tremendously in organizing my plants!

**Comment by danielbrendel** [comment]
You're welcome, glad you like it!
