### ISSUE TITLE
Ability to change invite url link

### ISSUE THREAD

**Issue by afairgiant** [danielbrendel/hortusfox-web#218]
**Description of your request**
Currently the invite user email provides a link to the internal IP address of the server.

**Describe the solution you'd like**
During the new user creation, would it be possible to have the login link url changed to a specified url if the site is externally accessible via reverse proxy? 

**Describe alternatives you've considered**
For the docker setup, you could have an optional environmental variable that would allow you to put the base url that would be used to access the site. 
Something like this: ` BASE_URL: https://foobar.com` 

**Additional context**
![image](https://github.com/danielbrendel/hortusfox-web/assets/20632147/9fbe15da-840f-4763-9be7-fd80ab730323)

**Comment by danielbrendel** [comment]
Resolved.
