### ISSUE TITLE
Ability to add pictures as an URL

### ISSUE THREAD

**Issue by hasecilu** [danielbrendel/hortusfox-web#219]
**Description of your request**
Have an alternative to be able to set an URL to set pictures, to avoid having to always upload the pictures.

**Describe the solution you'd like**
To have a text entry to enter the picture URL beside the "Upload" button.

**Describe alternatives you've considered**
Being able to read/choose pictures hosted on the server via a directory binding on the `docker-compose.yml` file. If you have specific dirs for plant pictures could be fine but if you have an application that manages the location of the pictures could not be the best option.

**Additional context**
Being able to set an URL instead of uploading a picture will enable users that self-host an image service to reuse the pictures that already have hosted and prevent to duplicate them.

I have my local-only [Immich](https://github.com/immich-app/immich) instance where I have quite some pictures of plants and when using HortusFox I have to re-upload them, effectively duplicating data on the server. This is not a big problem when you have a "small" quantity of plants but if you have a lot of plants and your pictures are high-quality could be.

On Immich you can share pictures publicly, permanently without password. When in the "shared picture" you do "Open Image in new Tab" you get an URL that you can use, I already tested in local markdown file and it renders correctly.

Example of Immich URL: `http://192.168.1.69:2283/api/assets/e70afe09-ef0f-4201-99bb-3d33ef754c95/thumbnail?size=preview&key=O3Gy1ABcdEf9vPURlb0c-GOzg2diVbSxj_KdnSonroIrOnS0SU5qEmHT9oXA3R3-h8A&c=YrgiKakANCR%2FZyEEuIqXySKbCrE%3D`

**Comment by danielbrendel** [comment]
That's a great idea! This will be worked on.

**Comment by hasecilu** [comment]
Yeah in my case files are available locally via `http`, could be that other users are using `https`, I think that even `ftp` or `smb` protocols could be viable as URL.
