### ISSUE TITLE
Question: Does anyone have config files for nginx or apache setups for hortusfox

### ISSUE THREAD

**Issue by brianw777** [danielbrendel/hortusfox-web#220]
I have the site working with the internal server but want to set this up alongside my grocy install on a vps and I am having trouble getting things to work with both nginx and apache2.

With nginx I have everything working (it seems anyway) except the admin page (well plant history isn't working but I am pretty sure that is just a db issue). When I click on the tabs the location bar shows the admin?tab=<selection> but the view stays on the Environment tab.

With apache2 I can bring up the main page but can't go to any other pages. All I get is page not found when selecting anything else.

If someone could point me to some documentation I can read I would appreciate it.

Thanks in advance,
Brian

**Comment by danielbrendel** [comment]
I haven't worked with nginx yet, so I can't say anything. But I have worked with apache on Ubuntu. Can you post your VirtualHost config?

**Comment by brianw777** [comment]
Thanks,

My apache2 config is just a very basic couple of lines from a simple example. I'll investigate the AllowOverride and work on getting the config right while waiting for the next release to come out. I can use the internal server while I am testing things so it isn't a big deal. I'll keep working at it.

With the self hosted web app grocy I worked on it 2 weeks with lighttpd before figuring out that it was lighttpd that was just to limited for it so switched to nginx. Now with nginx so dependant on external programs I may have to focus on apache.

I know this is configuration on my end and has nothing to do with hortusfox.

Thanks again, 
Brian

(I've taken up way too much of your time, sorry for that)

**Comment by brianw777** [comment]
Using the information you provided I still couldn't get it to work but it turns out I hadn't activated the rewrite mod. Once I did that, along with the changes from your information, it worked just fine.

`sudo a2enmod rewrite`

Thanks again for being patient with me and providing so much information.

Regards,
Brian
