### ISSUE TITLE
Please Publish Container Image

### ISSUE THREAD

**Issue by rwlove** [danielbrendel/hortusfox-web#231]
**Description of your request**
Publish your container image to Docker Hub or somewhere else.

**Describe the solution you'd like**
Make your container images publicly available.

**Describe alternatives you've considered**
Any public container registry will do.

**Additional context**
I don't want to build your images.

**Comment by danielbrendel** [comment]
Hi, is there any error shown? The docker image from GHCR is public, so you
should be able to clone/download the repo and then use `docker-compose
pull` & `docker-compose up -d` to download and launch the app.
