### ISSUE TITLE
Inventory,  missing location

### ISSUE THREAD

**Issue by tumeden** [danielbrendel/hortusfox-web#235]
**Describe the bug**
Missing a dropdown box of locations when adding inventory. 

**To Reproduce**

Go to Inventory,
Create New, 
Click location.  

**Expected behavior**
I would expect that the dropdown of all the locations would appear, however it's just a text box.
If this is intended, maybe consider adding a place for the admin to add 'inventory locations' which could be selected from the inventory 'location' area.   This would allow for a lot of more customization. 

**Screenshots**
![image](https://github.com/user-attachments/assets/89394e01-335d-437e-ba6e-7e5e9d275574)

**Software:**
- HortusFox version: v3.2

**Comment by tumeden** [comment]
![image](https://github.com/user-attachments/assets/9f013521-ab10-42cb-ac72-1b747e11c0d7)
Just had this happen after trying to edit an inventory item.

**Comment by danielbrendel** [comment]
> ![image](https://private-user-images.githubusercontent.com/45802712/348448007-9f013521-ab10-42cb-ac72-1b747e11c0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDg5MzMsIm5iZiI6MTcyMTA0ODYzMywicGF0aCI6Ii80NTgwMjcxMi8zNDg0NDgwMDctOWYwMTM1MjEtYWIxMC00MmNiLWFjNzItMWI3NDdlMTFjMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEzMDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTg1OWJhMjAyNTc5NjIxMGM4MWRkOWI1ZTQ2OTA0NGM3YWZkOGY3NTgzNGFlOWMxYWY3ZjIzNGFhMGU1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YRTtK5o2NMgu8E7KIDr1eiBDmtyBIch34CG0qw4m6A) Just had this happen after trying to edit an inventory item.

Can you try this again when ensured that the inventory item exists? If the problem still persists, please create a different issue, because it is not related to this issue and we want to keep things organized.

**Comment by danielbrendel** [comment]
Implemented via #235
