### ISSUE TITLE
Add polish translation

### ISSUE THREAD

**Issue by MBrylka** [danielbrendel/hortusfox-web#245]
I created a polish translation, and want to create a new branch with PR.

**Comment by danielbrendel** [comment]
Hi, thanks for your PR! It would be great if you could do it as gender neutral as possible, like you stated in your comment. In that case it would be good if you use the impersonal form. Thank you! I'll review further as soon as I find a minute.

**Comment by hermannhausherr** [comment]
Oh sorry, I just did it. I hope it is correct, I am pretty a novice with github and contributing

**Comment by danielbrendel** [comment]
References #246

**Comment by MBrylka** [comment]
Added new commit with impersonal for mas mentioned, cheers

**Comment by danielbrendel** [comment]
Resolved via d4f942590553307d909e4aa70b477607756a3e56
