### ISSUE TITLE
Auto backup

### ISSUE THREAD

**Issue by MBrylka** [danielbrendel/hortusfox-web#247]
**Description of your request**
Create auto backup mechanism

**Describe the solution you'd like**
Creating an auto backup mechanism for example to volume in docker image.
Lets say I have a network folder that I want to backup to I can mount this folder to a volume so application will do a backup in set intervals

**Comment by danielbrendel** [comment]
That's definitely useful. I'll evaluate this feature further.

**Comment by danielbrendel** [comment]
Resolved.
