### ISSUE TITLE
Allow larger picture size

### ISSUE THREAD

**Issue by Whatsek** [danielbrendel/hortusfox-web#251]
**Description of your request**
Picture-upload seems limmitted to 5Mb pictures, my camera shoots with 12-ish Mb

**Describe the solution you'd like**
It would be nice to define a max upload size with a docker environment variable.

**Describe alternatives you've considered**
I have read that instead of uploading a picture, you could make a live photo with the camera, but that option does not popup on my Android phone. (Using PWA app, Nothing Phone 2, android 14)

**Comment by danielbrendel** [comment]
What picture sizes do you have? Currently the limit is 5GB. But I agree that there needs to be a better way to adjust it. Before that you could manually change the limits in the 99-php.ini if you are using docker. Otherwise it depends on your php.ini settings file.

Also regarding your last paragraph: What version of HortusFox are you using?

**Comment by Whatsek** [comment]
My pictures are around 15-20Mb, I will modify the php.ini file to test.
I am using version HortusFox v3.1. in Docker on Synology NAS.
Thanks!

**Comment by Whatsek** [comment]
In the current docker, in 99-php.ini the limit is already set on15M:

```
upload_max_filesize = 15M
post_max_size = 15M
```
Although I get errors with files more then 5M

**Comment by danielbrendel** [comment]
What error are you getting?

**Comment by Whatsek** [comment]
This is the error uploading images larger then 5Mb: 

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /var/www/html/app/modules/UtilsModule.php on line 203

**Comment by Whatsek** [comment]
Hi @danielbrendel I just installed the latest release (3.7) and the upload of larger pictures works fine now! Thanks!

**Comment by danielbrendel** [comment]
That's great! Thanks for the feedback.

**Comment by danielbrendel** [comment]
Resolved.
