### ISSUE TITLE
Global save when adding multiple attributes

### ISSUE THREAD

**Issue by lockheed** [danielbrendel/hortusfox-web#254]
**Description of your request**
I was just adding attributes in bulk and found out painfully only one attribute can be saved at a time. 

**Describe the solution you'd like**
Can you add "global save" instead of just single  "save" per row?

**Comment by danielbrendel** [comment]
Do you mean that you have some kind of form where you can add attributes and then save them altogether? I see this could save some time as opposed when you add attribute by attribute having a new request to the server and wait for the response each time.

**Comment by lockheed** [comment]
![image](https://github.com/user-attachments/assets/701eb50b-f514-4815-86e9-ff2ffe2ed7b4)

Imagine you are here, rearranging attributes. 

You want to "Frost" from #15 to #5. Good luck not loosing your mind when after you manually cut/past everything in between these to shift them down and make space for new #5 (because there's no drag-drop functionality) and click "Update" only to discover that only ONE of the rows got saved and all the others reverted.

**Comment by danielbrendel** [comment]
Resolved.
