### ISSUE TITLE
Url Attribute 

### ISSUE THREAD

**Issue by tamaskan** [danielbrendel/hortusfox-web#257]
A clickable url-attribute would be nice to open a new tab to the wikipedia-page or the store you bought the plant from
Maybe with a tiny button to the web.archive.org-waybackmaschine of the page

**Comment by danielbrendel** [comment]
Hi, I pushed a [commit](https://github.com/danielbrendel/hortusfox-web/commit/78d5ce30b4b5337ebc3bd3455534a418cd2f65ee) that now enables that any text attribute that contains an URL will be rendered as a link. So you can then define custom attributes like "Shop bought from" or anything else and set an URL. I hope that would be sufficient for your request.
