### ISSUE TITLE
500 Internal Server Error when image resource not found

### ISSUE THREAD

**Issue by afyounie** [danielbrendel/hortusfox-web#258]
**Describe the bug**
500
Internal Server Error
Exception at /var/www/html/vendor/danielbrendel/asatru-php-framework/src/helper.php:199
Reported error: Resource "img/52b3f17378688b1d57e3ba393e03a319_thumb.jpg" not found on server.
[Refresh](javascript:void(0);)
Stack trace:
#6 /var/www/html/app/modules/UtilsModule.php(535): asset ( 'img/52b3f17378688b1d57e3ba393e03a319_thumb.jpg' )
#5 /var/www/html/app/helper/AppHelper.php(102): UtilsModule::absolutePhoto ( '52b3f17378688b1d57e3ba393e03a319_thumb.jpg' )
#4 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(416) : eval()'d code(444): abs_photo ( '52b3f17378688b1d57e3ba393e03a319_thumb.jpg' )
#3 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(416): eval
#2 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(764): Asatru\View\ViewHandler::out
#1 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(124): HandleView ( Asatru\View\ViewHandler )
#0 /var/www/html/public/index.php(25): require_once ( '/var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )

**To Reproduce**
1. Create a plant
2. Add an image using external URL
3. Clone the plant

**Expected behavior**
I expected it to clone the plant with the same exact resources and then allow me to replace them without breaking the UI.

**Screenshots**
![Screenshot_2024-08-18_18-01-44](https://github.com/user-attachments/assets/898faeed-9351-46ed-9851-ba67c8973844)

**Software:**
- HortusFox version: latest from ghcr.io
- Podman 4.4.1
- Changes to your docker-compose file if altered: changed port to 3000

**Desktop (please complete the following information):**
 - OS: linux mint 21
 - Browser: firefox

**Smartphone (please complete the following information):**

**Comment by afyounie** [comment]
I want to add that I am unable to delete the problem plant. It isn't available from the dashboard, but if I go to directly to it's page, I get what you see in the screenshot. There are no buttons to remove the plant.
![Screenshot_2024-08-18_18-06-00](https://github.com/user-attachments/assets/35274e69-a53d-4a5e-8e42-c80096a23d66)

**Comment by danielbrendel** [comment]
Hi, thanks for reporting that bug. I'll add a fix for this asap.
