### ISSUE TITLE
Internal server error on the admin page

### ISSUE THREAD

**Issue by Zo-ey** [danielbrendel/hortusfox-web#260]
**Describe the bug**

I am getting an internal server error when trying to access the admin pannel> The error message is displayed in the banner.

Error message:
`500
Internal Server ErrorException at /home/xxxx/hortusfox-web/app/modules/UtilsModule.php:247
Reported error: Call to undefined function locale_get_display_language()
RefreshStack trace:#4 /home/xxxx/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/view.php(416) : eval()'d code(265): UtilsModule::getLanguageList#3 /home/xxxx/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/view.php(416): eval#2 /home/xxxx/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/view.php(764): Asatru\View\ViewHandler::out#1 /home/xxxx/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(124): HandleView#0 /home/xxxx/hortusfox-web/public/index.php(25): require_once ( '/home/xxxx/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )`

**To Reproduce**
1. Login with your initial admin user account after a fresh install
2. Click on 'Admin Area'

**Expected behavior**
A display of the admin panel.

**Software:**
- HortusFox version: 3.3
- PHP Version: 8.3.10

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox 129.0.1

**Additional context**
I am sorry if this problem comes from my inexpertise. Web development is not one of my programming skills, I just wanted to try this app that seems pretty cool :). 
I used a freshly installed Xampp with default configuration, except for what is indicated in the troubleshooting section [here](https://wiki.archlinux.org/title/XAMPP), and the indicated patch [here](https://stackoverflow.com/questions/1676688/mysql-connection-not-working-2002-no-such-file-or-directory). Thank you for all this work!

**Comment by danielbrendel** [comment]
Hi, you need to enable the intl extension in your php.ini.

See here: https://stackoverflow.com/a/53013744
