### ISSUE TITLE
Ability to change URL for sharing plant fotos

### ISSUE THREAD

**Issue by m4nges** [danielbrendel/hortusfox-web#261]
**Description of your request**
Sharing photos is currently only possible via the URL https://www.hortusfox.com. 

**Describe the solution you'd like**
I would like to share the photos via my own domain. 

**Describe alternatives you've considered**
For the docker setup, you could have an optional environmental variable that would allow you to put the URL that is used for sharing.
Something like ‘SHARE_PHOTO_URL:

**Comment by danielbrendel** [comment]
Yes, we can implement this for the next update. Thanks for the suggestion.
