### ISSUE TITLE
Deprecated Warning in Placeholder

### ISSUE THREAD

**Issue by tamaskan** [danielbrendel/hortusfox-web#266]
Inside "optional place for backup files"
and mail "reverse proxy"

<br /><b>Deprecated</b>:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(416) : eval()'d code</b> on line <b>846</b><br />

**Comment by danielbrendel** [comment]
Did you upgrade from 3.3 to 3.4 or did you do a fresh installation? Did you
modify anything?

**Comment by danielbrendel** [comment]
I can see now this happens on a fresh installation. You can just remove the
error message and click save, so it will be empty then. I'll fix that for
the next release. Thanks for reporting.
