### ISSUE TITLE
Sort/Filter custom attributes

### ISSUE THREAD

**Issue by ozymandias1688** [danielbrendel/hortusfox-web#267]
Currently, we can sort plants by some default attributes or we can do a full-text search of the names, tags and notes. Querying any custom-defined fields is not possible, however.

It would be awesome, if we could also sort/filter custom-created attributes. Is it possible to include this?

Alternatively, we could of course just use labels, but that kind of defeats the purpose of custom fields.

Thanks!

**Comment by danielbrendel** [comment]
Resolved.
