### ISSUE TITLE
Plant Photo covering table

### ISSUE THREAD

**Issue by afairgiant** [danielbrendel/hortusfox-web#280]
**Describe the bug**
When the computer browser window is narrower than 1475 pixels the photo starts covering up the table information. It will eventually go below the table at 768 pixels wide. I used firefox's responsive design mode to test out what pixel width it happened at. 

**To Reproduce**
Go to a plant photo detail page and make your browser window narrower. 
Occurs with the default image as well as uploaded images. 

**Expected behavior**
The photo should either go below the table or scale accordingly, depending on the size of the window.

**Screenshots**

![image](https://github.com/user-attachments/assets/49d9323a-45a2-4d1d-a70e-5254b6bb465a)
![image](https://github.com/user-attachments/assets/80a32fa2-ac69-4ab5-8eb5-8911460ffb3f)
![image](https://github.com/user-attachments/assets/95e28777-f5da-4cd6-9704-87404050f0dc)

**Software:**
- HortusFox version: v3.5
- PHP Version: 8.3.0
- Docker version if used in a docker environment: 27.3.1
- Changes to your docker-compose file if altered: N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox(Version 130.0.1) & Chrome (Version 129.0.6668.90)

**Comment by danielbrendel** [comment]
Should be resolved now.
