### ISSUE TITLE
User Journal or Location Journal

### ISSUE THREAD

**Issue by ilgigante77** [danielbrendel/hortusfox-web#287]
**Description of your request**
It would be nice to have a user personal gardening journal and/or location-wise journals.

**Describe the solution you'd like**
Journal with entries in a calendar or in a list chronologically, with an optional title, a markdown compatible body and optional links to one or more plant log entries.

**Describe alternatives you've considered**
Insert dummy plants with the journal entries as plant log entries.

**Additional context**
n.a.

**Comment by danielbrendel** [comment]
Hi, thanks for your request. This is a duplicate of https://github.com/danielbrendel/hortusfox-web/issues/283 and will be worked on in that particular issue.
