### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by alexppg** [danielbrendel/hortusfox-web#294]
Hello there
Thanks for this project, I like it so far :)
I've made a helm chart for deploying in hortus-fox in kubernetes. It's quite basic, but I think the basics are covered. Are you interested in adding it this repository? I can host it without problem, I already have some charts in here: https://github.com/little-angry-clouds/charts/.
See ya

**Comment by danielbrendel** [comment]
Hi there, glad you like the project.

There are a number of platforms and toolsets for deployment and
infrastructure which is a hassle to support given that I'm a single person.
So, unfortunately I have to reject this request. I prefer to stick to
developing the core project repositories, but if the community decides to
create deployment config files and they get a lot of traffic / getting
credible as they grow then I'd be open to mention these in the
documentation under "Community hosting". But I personally am not willing to
dive into all these deployment platforms (also given that kubernetes / helm
charts rarely come up as requests). Sidenote: Adding helm chart configs
would also need to have a separate repository.

Thanks for your understanding.

Kind regards
