### ISSUE TITLE
3.7 bugs

### ISSUE THREAD

**Issue by kaleben0** [danielbrendel/hortusfox-web#300]
A couple small issues with 3.7

- When in list view of your plant, if you try to sort the list, it switches back to card view
- When disabling tasks, the Task Count on the main page is still visable
- When searching for a plant using the Pl@ntNet API, it should probably have a confirm screen before applying the information
  - Example : When I tried to have it identify my Purple Coneflower, it didn't get it right and applied what it thought it was without confirmation.

**Comment by danielbrendel** [comment]
Hi, thanks for the feedback! These issues have been resolved now.

**Comment by kaleben0** [comment]
Thank You!
