### ISSUE TITLE
Failed DB Connection

### ISSUE THREAD

**Issue by sudodaemon** [danielbrendel/hortusfox-web#301]
**Describe the bug**
Not able to get Hortusfox started, using docker compose, in the app container it just repeats "Waiting for database to be available... Attempt 21"

and in the DB container the logs show "[Warning] Aborted connection 20 to db: 'unconnected' user: 'unauthenticated' host: '192.168.112.3' (This connection closed normally without authentication)"

**To Reproduce**
1. Configure docker compose, run it, no errors when running docker-compose

**Expected behavior**
Make a DB connection

**Screenshots**

**Software:**
- HortusFox version - Latest, 3.7
- PHP Version
- MySQL version : Latest
- Changes to your docker-compose

`version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    ports:
      - "9099:80"
    volumes:
      - app_images:/var/www/html/public/img
      - app_logs:/var/www/html/app/logs
      - app_backup:/var/www/html/public/backup
      - app_themes:/var/www/html/public/themes
      - app_migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: "me@gmail.com"
      APP_ADMIN_PASSWORD: "password1"
      APP_TIMEZONE: "EST"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: username
      DB_PASSWORD: password1
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: username
      MYSQL_PASSWORD: password1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate:
`

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04.6

**Additional context**
I swear I'm not a docker newbie, I have a ton of other containers using mysql, or postgres... I just can't get this going and I'm sure its a simple thing I'm overlooking.

**Comment by danielbrendel** [comment]
Hi, I'm sorry it's not working on your end.
This is very likely a configuration issue. I'd advise to join our Discord
or use the support form in order to get usage help.
Kind regards

Support contact form: https://www.hortusfox.com/support
Discord server: https://discord.gg/kc6xGmjzVS

**Comment by etorres4** [comment]
Hi! I was having the exact same problem as you. I was actually able to fix this problem by manually running these commands on the mariaDB container:

Note: replace the <> with whatever values you used

    // (from your system's shell
    $ docker compose exec db mariadb -u root
    // (in mariadb shell in the container)
    $ use mysql;
    // hortusfox is the username here before the @
    $ CREATE USER '<mysql_user>'@'%' IDENTIFIED BY '<mysql_password>';
    // Create the database
    $ CREATE DATABASE <mysql_database>;
    // We need to give the hortusfox user access to the hortusfox database
    $ GRANT ALL ON <mysql_database>.* TO '<mysql_user>'@'%';
    $ FLUSH PRIVILEGES

For whatever reason not sure why, the database itself wasn't being set up. These commands manually run the steps needed for the app to communicate properly with the database.

**Comment by danielbrendel** [comment]
Solution provided by user.
