### ISSUE TITLE
SQL-Issue

### ISSUE THREAD

**Issue by gstoetti94** [danielbrendel/hortusfox-web#302]
**Describe the bug**
HortusFox is run on Docker. I upgraded to v 3.7.
When trying to edit items in Administration-Environment, I get the error message:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'custom_media_share_host' in 'field list' `

It occured when I tried to add the Pl@ntNet-API.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/c928e3bf-6ef4-461f-b914-01e866891475)

**Software:**
- HortusFox version 3.7
- PHP Version 8.3.0
- MySQL version 10.11.9-MariaDB-ubu2004
- Changes to your docker-compose file if altered: External DB-Server (no docker-image)

**Comment by danielbrendel** [comment]
Hi, sorry that you run into these issues.

I'm suspecting that you updated HortusFox from a version prior to 3.5.

In order to solve this, please run the following commands:

```
php asatru migrate:upgrade 3.5
php asatru migrate:upgrade 3.6
php asatru migrate:upgrade 3.7
```

**Comment by gstoetti94** [comment]
Perfect, thank you.

Running the Command 
`sudo docker exec [containername]  php asatru migrate:upgrade 3.7`
solved the issue.

**Comment by gstoetti94** [comment]
Perfect, thank you.

Running the Command 
`sudo docker exec [containername]  php asatru migrate:upgrade 3.7`
solved the issue.
