### ISSUE TITLE
Feature Request : Havested

### ISSUE THREAD

**Issue by kaleben0** [danielbrendel/hortusfox-web#303]
**Description of your request**
Like "set watered" and "set fertilized", it would be cool if there was also a way to "set harvested"  to track when a fruit/vegetable/herb was last harvested. 

Example : I just harvested a bunch of herbs this morning and this would help to make sure I am not harvesting them too quickly.

**Comment by danielbrendel** [comment]
Hi, you can add custom location specific actions via the admin dashboard
in the attributes section (Custom bulk commands):

   - Label: The button label (Set harvested)
   - Attribute: Your actual custom attribute (e.g. last_harvested)
   - Style: CSS color style (e.g. background-color: violet; color: white;
   border: 1px solid rgb(255, 0, 100);)

I have planned to create a video tutorial for that feature, but I hope this
helps in the meantime.

**Comment by kaleben0** [comment]
I did not know I could do that. That is great! Thank You!
