### ISSUE TITLE
Weathermap issue NOT resolved in v3.8

### ISSUE THREAD

**Issue by dghoti** [danielbrendel/hortusfox-web#309]
unable to reopen existing issue - but have updated with compose.yml and other information (
 https://github.com/danielbrendel/hortusfox-web/issues/306#issue-2666325957 )

![image](https://github.com/user-attachments/assets/936548f0-c163-49a7-b60f-ee223121150e)

**Comment by danielbrendel** [comment]
Hi, I just looked into it and you're right. This is a weird thing, but it
will happen in like 1 in 3 time zones. The ones across the globe I tested
them with coincidentally worked, but the others won't. I will provide a fix
within the next version. However, this will take at least until next month
or maybe even the new year.

Notes:
- There are different base times depending on the time zone, which is
either 1:00, 2:00 or 3:00. Also examine depending behaviour for DST.
- Completely refactor the forecast algorithm

**Comment by dghoti** [comment]
Thanks for looking into it - apologies for being a pain, but this is an (annoying) part of an otherwise fantastic app! Thanks for your time, and no worries on a fix - but thought it was important that I update you as I was trying it anyway. On the upside - Im a dab hand at spinning up instances now ;)

**Comment by danielbrendel** [comment]
No worries! I appreciate the responses. Sometimes features are a bit hard to test in call cases, but this is really helpful!

**Comment by danielbrendel** [comment]
I've just published an update. Does it now work for you?

**Comment by dghoti** [comment]
I can confirm this now works perfectly, as intended!
![image](https://github.com/user-attachments/assets/98a03d1b-0958-4551-aee3-aa490efc063f)

A personal note of preference - I would prefer it to be a bit less spaced out, so I can see a full day in one screen, but that is just an observation. Thank you for taking the time to resolve this and improving an already good app even further! 👍

**Comment by danielbrendel** [comment]
Resolved.
