### ISSUE TITLE
500 Error Unknown character set

### ISSUE THREAD

**Issue by criostage** [danielbrendel/hortusfox-web#311]
**Describe the bug**
When attempting to install Hortusfox-web in a docker server i get the error following error: **Exception at /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php:1198** **Reported error: SQLSTATE[HY000] [2019] Unknown character set**

**To Reproduce**
This is how i attempted to install on my server
1. Created and configured an Standard MariaDB Database Server on container in Proxmox
2. Created a MariaDB database (Hortusfox), a user (hortusfox) and granted full permissions of this user to the database. Database collation is set to the default value of **utf8mb4_general_ci**
3. Edited my Apps yaml file hosted in github by adding the following:
4. Pulled the yaml file from Github on Portainer and tried to access the url Hortusfox.local.domain. I get presented with the 500 error with the following description: **Exception at /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php:1198** **Reported error: SQLSTATE[HY000] [2019] Unknown character set**

**Expected behavior**
To be allowed to install Hortusfox on my server without issues

**Software:**
- HortusFox version: 3.8
- PHP Version 8.3.0
- MySQL version (if related to the problem): 10.11.8-MariaDB-0ubuntu0.24.04.1
- Docker version if used in a docker environment: 26.1.4, build 5650f9b
- Changes to your docker-compose file if altered:

  Hortusfox-web:
    hostname: "hortusfox"
    image: "ghcr.io/danielbrendel/hortusfox-web:latest"
    container_name: "Hortusfox-web"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_public
    environment:
      - APP_ADMIN_EMAIL="admin@example.com"
      - APP_ADMIN_PASSWORD="change_password"
      - APP_TIMEZONE=${TZ}
      - DB_HOST=${MariaDBHost}
      - DB_PORT=3306
      - DB_DATABASE=${MariaDB_HortusFoxDB}
      - DB_USERNAME=${MariaDB_HortusFoxUser}
      - DB_PASSWORD=${MariaDB_HortusFoxPwd}
      - DB_CHARSET="utf8mb4"
    volumes:
      - ${DOCKERDIR}/hortusfox/data/images:/var/www/html/public/img
      - ${DOCKERDIR}/hortusfox/data/backup:/var/www/html/public/backup
      - ${DOCKERDIR}/hortusfox/data/themes:/var/www/html/public/themes
      - ${DOCKERDIR}/hortusfox/data/migrations:/var/www/html/app/migrations
      - ${DOCKERDIR}/hortusfox/logs:/var/www/html/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Hortusfox.entrypoints=http"
      - "traefik.http.routers.Hortusfox.rule=Host(`Hortusfox.${PrivateDomain}`)"
      - "traefik.http.middlewares.Hortusfox-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.routers.Hortusfox.middlewares=Hortusfox-redirectscheme"
      - "traefik.http.routers.Hortusfox-secure.entrypoints=https"
      - "traefik.http.routers.Hortusfox-secure.rule=Host(`Hortusfox.${PrivateDomain}`)"
      - "traefik.http.routers.Hortusfox-secure.tls=true"
      - "traefik.http.routers.Hortusfox-secure.service=Hortusfox"
      - "traefik.http.services.Hortusfox.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_public"

Note: I do not expose any ports as i have a Traefik instance to access containers, and i can confirm it is working as i get the Asatru PHP Framework 500 error with the error mentioned above. Also i use variables to populate the configuration.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 24H2
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22] 131.0.2903.70

**Additional context**

**Comment by kaleben0** [comment]
You could try manually setting it in case something did not set right.

ALTER DATABASE your_hortusfox_database
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

**Comment by criostage** [comment]
Thank you for your input @kaleben0, I was almost sure that the database was already using that charset and collate but I followed your suggestion and ran it anyway. Unfortunately I still get the same result:
![image](https://github.com/user-attachments/assets/8a76b5dd-f340-4c32-9b20-2022360990f2)

This is the error in the docker container:
![image](https://github.com/user-attachments/assets/7c6d8c3d-fe79-4451-a970-79118f0441df)

and this when I access using the browser:
![image](https://github.com/user-attachments/assets/cf1c6d75-4659-459c-8b28-7c8694204e10)

**Comment by danielbrendel** [comment]
Hi, sorry that it's not working on your end.

From looking at your docker-compose it seems that only the DB_CHARSET is
not populated. You're using some variables such as `${MariaDB_*}`, maybe
you need to create another one for DB_CHARSET here? I'm not familiar with
proxmox and traefik, but your error message indicates that this environment
variable is not populated, so it just passes an empty string as charset
specifier.

Unfortunately the entrypoint script does not specify a fallback charset
value, which also supports the assumption that this is exactly the issue
here. I'll add this with a next commit. Until then you can try to create a
MariaDB_ variable for DB_CHARSET.

**Comment by criostage** [comment]
Hello @danielbrendel, thank you for your reply. While reading your post i went back and checked in Portainer the variables being passed to docker container. Here I noticed two things: the DB_CHARSET was indeed populated and secondly the value was "utf8mb4". At first glance, the configuration seemed okay but then i remembered i had this problem in the past with another application. Once i removed the quotes on the DB_CHARSET variable under environment it started to work. Here's what i changed:

environment:
- APP_ADMIN_EMAIL=admin@example.com
- APP_ADMIN_PASSWORD=change_password
(...)
- DB_CHARSET=utf8mb4

Looking a little deeper, indeed the syntax I'm using it seems its slightly different from example file on this repo: while the environment variables are set like this **DB_CHARSET: "utf8mb4"** on mine, i used it like this (the working version) **- DB_CHARSET=utf8mb4**. They are both acceptable but i guess if i add an equal sign i cannot put the quotes or else the quotes will be passed down as being part of the variable

**Comment by criostage** [comment]
Hello @danielbrendel, thank you for your reply. While reading your post i went back and checked in Portainer the variables being passed to docker container. Here I noticed two things: the DB_CHARSET was indeed populated and secondly the value was "utf8mb4". At first glance, the configuration seemed okay but then i remembered i had this problem in the past with another application. Once i removed the quotes on the DB_CHARSET variable under environment it started to work. Here's what i changed:

environment:
- APP_ADMIN_EMAIL=admin@example.com
- APP_ADMIN_PASSWORD=change_password
(...)
- DB_CHARSET=utf8mb4

Looking a little deeper, indeed the syntax I'm using it seems its slightly different from example file on this repo: while the environment variables are set like this **DB_CHARSET: "utf8mb4"** on mine, i used it like this **- DB_CHARSET=utf8mb4**. They are both acceptable but i guess if i add an equal sign i cannot put the quotes or else the quotes will be passed down as being part of the varialble
