### ISSUE TITLE
Retain plant pictures when updating cover picture

### ISSUE THREAD

**Issue by dghoti** [danielbrendel/hortusfox-web#312]
**Description of your request**
When adding or updating the plant picture, rather than replacing the current picture (the current behaviour) could the picture be transferred to the gallery instead - so a history of the plants progress can be kept? each picture adds to the gallery, which can be deleted manually, rather than automatically. Possibly, an option can be given to replace or add as the user desires.

**Describe alternatives you've considered**
The only current alternative that I can imagine is to download the current plant picture, then upload it to the plant gallery manually then upload a new plant cover image.

**Additional context**
Ideally the most recent picture would become the cover photo for the plant - and as such would be more recognisable than a (possibly) months old picture
![image](https://github.com/user-attachments/assets/bfdab376-09de-487b-8d6e-8e351b0bf8d6)
In this image adding a new image via [1] would add the current picture to the "Photos" Gallery, instead of having to download and then manually upload to [2]

**Comment by dghoti** [comment]
This is a great improvement, thank you!
![image](https://github.com/user-attachments/assets/398eb8ae-b228-4535-8d6f-7a167e9dd54f)

I am being fussy here, but is there a way to make this ticked by default (or user configurable?) - but this is a fantastic time saver and extremely superior! Thank you for adding this!

**Comment by dghoti** [comment]
having used it a few times - maybe retain the original upload time, rather than use the "replacement time"
![image](https://github.com/user-attachments/assets/d86706d3-2bf1-4bba-bbba-6a2369fdf237)
As you can see, the original photo was uploaded 24 th November, when the plant was added, but having been replaced with a new cover photo, it now shows creation time of only a few hours, instead of several weeks.. (still a fantacstic feature though!)

**Comment by kaleben0** [comment]
This might still need some work. I took a new picture and it saved two copies of the old pic to the gallery. I went to delete one and it started giving me 500 errors because it could not find that picture anymore. 
Restored the database from last night's backups, and it is fine now.

**Comment by kaleben0** [comment]
I don't have the error anymore, but it basically was freaking out because it could not find the duplicate image anymore. I think the delete option didn't remove all references to the image which spawned the error. 
I tried going into the database and removing the reference manually, but that didn't work either.

**Comment by danielbrendel** [comment]
@dghoti you're right, that would be better for organizing.

@kaleben0 I updated it so that when a gallery asset is nonexistent then the system will display the placeholder instead, so no error 500 anymore.
