### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by danielbrendel** [danielbrendel/hortusfox-web#45]
Add more languages in order to support a broader audience.

**Comment by nykroy** [comment]
Can i help you to translate with spanish?

**Comment by danielbrendel** [comment]
> Can i help you to translate with spanish?

Sure, you can make a PR with a localization for spanish.
You'd just need to use app/lang/en as base and copy it to app/lang/es and translate the english phrases.

**Comment by maaknaamaan** [comment]
I'm like 90% done with the Dutch translation, but how do I get to preview the language to see it in action? It's in a separate directory de/en/**nl** but the language doesn't show up on the settings panel.

**Comment by danielbrendel** [comment]
Do you have the following files in place?
```
/app/lang/nl/app.php
/app/lang/nl/errors.php
/app/lang/nl/tb.php
```

And did you set the `_language_ident` token in your `/app/lang/nl/app.php`?

**Comment by krinkuto11** [comment]
Hi, I have a Spanish translation ready to upload. How may I proceed? Thanks

**Comment by danielbrendel** [comment]
Hi, you can make a pull request via GitHub, so I can review it. Basically you'll need to fork the repository, make your changes and then create a PR on GitHub. On successful review I can then merge your changes into the repository.

**Comment by danielbrendel** [comment]
Info: We are still looking for translations into languages like french, italian, portugese, norwegian, dutch, swedish, and others you may want to localize.

**Comment by danielbrendel** [comment]
For the next v3.2 add french translation: #223

**Comment by brianw777** [comment]
Question: Most of my plants are outside in traditional and raised bed gardens so I did a fork and I am working on a last_weeded attribute. I was looking at the translations and didn't know if I needed to do them for my change or not. I used online translators to find the best ones for the da,de and es translations but I am not sure if I should do those or not?

**Comment by brianw777** [comment]
Sorry Daniel I didn't really explain that properly. I didn't mean the name of the attribute but the translations within the app/lang/?? files. Like this:

For the Danish translations:
app/lang/da/app.php

> 'last_weeded' => 'Sidste træk ukrudt',
> 
> 'sorting_type_last_weeded' => 'Sidste træk ukrudt',
> 
> 'calendar_class_weed' => 'Ukrudt',
> 
> 'set_weeded' => 'Sæt ukrudt trukket',
> 'bulk_set_weeded' => 'Sæt planter til ukrudt trukket',
> 'confirmSetAllWeeded' => 'Er du sikker på, at du vil opdatere den sidste ukrudtsdato for alle disse planter?',
> 'all_plants_weeded' => 'Sæt planter til ukrudt trukket',

Similar for the app/lang/de/app.php and app/lang/es/app.php files

The English file app/lang/en/app.php would contain:

> 'last_weeded' => 'Last weeded',
> 
> 'sorting_type_last_weeded' => 'Last time weeded',
> 
> 'calendar_class_weed' => 'Weeding',
> 
> 'set_weeded' => 'Set weeded',
> 'bulk_set_weeded' => 'Set plants to weeded',
> 'confirmSetAllWeeded' => 'Are you sure you want to update the last weeded date of all these plants?',
> 'all_plants_weeded' => 'Last weeded status has been updated for these plants.',

My question is I know I have to do the English en/app.php file but do I also do the translations for those da,de,es and now fr app.php files using online translators (and hopefully have someone check them later) or do I leave them and they get done under a different issue/pull request or something else?

As seen above I have already done them for everything except the French so they would just need to be checked by someone (I would also do the French using online translators). Would I open a separate issue as enhancement and then submit them separately? Just trying to figure out the best process for getting the translations done for an enhancement like this.

Sorry for the confusion and thanks,
Brian

**Comment by danielbrendel** [comment]
Ok, what kind of attribute is yours? A custom one or did you implement a
default attribute?

Generally translations are optional. You'd only translate phrases that you
need (in the context of your own custom fork).

If there is no translation found then it just returns the phrase identifier.

**Comment by brianw777** [comment]
"Ok, what kind of attribute is yours?"

I am working on an attribute for last_weeded (like last_watered, last_repotted and last_fertilised) for outdoor gardeners. I was hoping that it might be useful to others and I would generate a pull request to see if you are interested.

When I was testing it before I had added a button for setting plants to weeded and that is what made me find out that buttons did not hide when the attribute was unchecked.

I am going to make the changes to the updated code in my repo and then submit a pull request. If you like the idea you can add it and if you don't find it useful I can keep it in my own repository.

**Comment by danielbrendel** [comment]
Ah, I see. Tho I have decided to not include any further default
attributes, because it can be subjective what default attribute is useful
to what party. While I agree that last weeded is definitely useful for
outdoor gardening, it is something that most indoor plant parents would
most likely not use (the initial target audience for HortusFox). That's why
the best approach would be to just use a custom attribute to fit the
specific needs of the user. I appreciate the work you put behind that, but
I'd have to reject that PR, unfortunately. But of course you can use it on
your own fork!

Regarding your initial question: If you want to translate last_weeded for
your fork, then you can add it to the other language files. When you are
using the localization helper like `__('app.last_weeded')` the underlying
framework will try to find a translation for the current language of the
client. If it doesn't find a translation phrase then it will return the
related identifier like `app.last_weeded`.

I don't know what your native language is, but as a workspace admin, you
can also specify the default language of your workspace. Tho users can
change their own language in their preferences.

I hope this helps, please let me know if you have further questions.

**Comment by brianw777** [comment]
Okay. I understand and thank you for letting me know.

Regards,
Brian

**Comment by danielbrendel** [comment]
Further languages need their own issue/PR.
