### ISSUE TITLE
Add github action workflow to automatically build docker image on push

### ISSUE THREAD

**Issue by InputObject2** [danielbrendel/hortusfox-web#74]
Publish the docker container to ghcr with the default workflow (can be configured from the "marketplace") directly on github. Having a pre-built publicly available image should help with adoption.

**Comment by danielbrendel** [comment]
I also found a neat video on youtube that explains this pretty well. 

Btw @InputObject2 and @iandday just want to thank you for your contributions so far! It's nice to see other devs actively participating in this project.

**Comment by danielbrendel** [comment]
A new image will now be built when a new version tag is published. This ensures that users will not pull from the main branch, but rather from stable versions. 
I also consider to jump directly to version 2.0 for the next release due to the recent major changes.
