### ISSUE TITLE
Unable to Upload JPEG

### ISSUE THREAD

**Issue by inextricable-code** [danielbrendel/hortusfox-web#92]
Whilst trying the newest version (main) I am still unable to upload a picture, and therefore cannot add any plants. 

The error I'm getting now is as follows, 

`Notice: ob_clean(): Failed to delete buffer. No buffer to delete in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/exception.php on line 25`

And the stack trace is, 

`#5 /var/www/html/app/models/PlantsModel.php(223): UtilsModule::createThumbFile ( '/var/www/html/public/img/d6cc2951c24429ced72ce500d061e716.jpg' , int(2) , '/var/www/html/public/img/d6cc2951c24429ced72ce500d061e716' , 'jpg' )
#4 /var/www/html/app/controller/plants.php(151): PlantsModel::addPlant ( 'Bromiliad Guzmania' , '2' , bool(false) , '50' , 'light_level_half_shade' )
#3 internal function: PlantsController::add_plant ( Asatru\Controller\ControllerArg )
#2 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/controller.php(575): call_user_func ( array , Asatru\Controller\ControllerArg )
#1 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(118): Asatru\Controller\ControllerHandler::parse ( '/plants/add' )
#0 /var/www/html/public/index.php(26): require_once ( '/var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )`

I've taken a look myself but I can't find what I'm doing wrong, any advice?

(Edit: I'm attempting to get this running on Unraid if that effects anything)

(Edit Edit: I just tried with a PNG file and that worked absolutely fine)

**Comment by inextricable-code** [comment]
I tried a 40KB file first, then a 4KB file as I had the same thought that it might be file size dependant. 
I also tried uploading straight from the Camera, but predictably had the same issue.

**Comment by danielbrendel** [comment]
I see. 40KB is really fine. I am unfamiliar with Unraid. This is a server operating system, isn't it? Sounds kinda strange tho that PNG file upload works nonetheless. 

Does this also fail if you use just a random JPG picture from the internet such as from unsplash or pexels?

Actually the notice shows something that I have to update in the framework. Meanwhile you can do the following to see why the exception is really thrown:

In the docker-entrypoint.sh you can change the following line (line 19 context configure_php_error_reporting):
```sh
 echo 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT' > /usr/local/etc/php/conf.d/errors.ini
```
to
```sh
echo 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE' > /usr/local/etc/php/conf.d/errors.ini
```

This way the notice will be surpressed when debug mode is enabled, so the actual cause of the exception should be shown.

**Comment by danielbrendel** [comment]
You can now try to clone/update from main branch again since I have updated the underlying framework.

**Comment by inextricable-code** [comment]
I've just managed to upgrade to the new version, and I can confirm that version 2.0 fixes this issue and I can upload JPEG's and PNG's, both directly from the camera and downloaded images.
Thank you for fixing this

**Comment by danielbrendel** [comment]
Glad it works now!
