### ISSUE TITLE
Can't pull

### ISSUE THREAD

**Issue by JFPCreations** [danielbrendel/hortusfox-web#96]
I'm not sure if it's on my side but I can't figure out what is the problem.

failed to deploy a stack: app Pulling app Error Error response from daemon: Head "https://ghcr.io/v2/danielbrendel/hortusfox-web/manifests/latest": unauthorized

Thank you.

**Comment by danielbrendel** [comment]
It was accidentally set to private. It's now set to public. Does it work now on your end?

**Comment by JFPCreations** [comment]
@danielbrendel It worked thank you. But now I see that: 
![image](https://github.com/danielbrendel/hortusfox-web/assets/10256543/e99a0b34-51bd-43a1-a862-718d4590ff91)

**Comment by JFPCreations** [comment]
And after login, the top bar show : 
Deprecated
: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(416) : eval()'d code
on line
25

**Comment by danielbrendel** [comment]
Did you modify anything?
Can you check what's the value of `workspace` in your AppModel table in your database?

**Comment by gonsalvesc** [comment]
I'm getting the same error. 
My AppModel table is empty

**Comment by gonsalvesc** [comment]
Also getting this error when I check Portainer:

`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , , , , , 'History', true, '', , '', '', '', , '', '', '', CURRENT_TIMESTAMP)' at line 1`

**Comment by inextricable-code** [comment]
I'm also getting the, 
`"<br /><b>Deprecated</b>:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php(416) : eval()'d code</b> on line <b>184</b><br />" `
error as others are above.

For some reason, it places this error into the "Workspace" and the "History Name" fields in the GUI. And the "Environment" page doesn't save either, reverting back to stock settings no matter what.

**Comment by danielbrendel** [comment]
> Also getting this error when I check Portainer:
> 
> `ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , , , , , 'History', true, '', , '', '', '', , '', '', '', CURRENT_TIMESTAMP)' at line 1`

This looks like some of the values before 'History' are empty or not set. What are the values of your APP_* variables? If you use boolean, you need to set them in quotation like "true".

**Comment by gonsalvesc** [comment]
Thank you!
I just put all boolean in quotations and am still getting the same error. Here are my APP_* variables.

`# App settings
APP_NAME="HortusFox"
APP_VERSION="1.0"
APP_AUTHOR="Daniel Brendel"
APP_CONTACT="dbrendel1988@gmail.com"
APP_ADMIN_EMAIL="admin@example.com"
APP_ADMIN_PASSWORD="password"
APP_DEBUG="true"
APP_BASEDIR=""
APP_LANG="en"
APP_WORKSPACE="My home"
APP_ENABLESCROLLER="true"
APP_OVERLAYALPHA=null
APP_ENABLECHAT="true"
APP_ONLINEMINUTELIMIT=5
APP_SHOWCHAT_ONLINE_USERS="true"
APP_SHOWCHAT_TYPING_INDICATOR="true"
APP_OVERDUETASK_HOURS=10
APP_CRONPW="cgyy5v8ze996L7Cj"
APP_CRONJOB_MAILLIMIT=5
APP_GITHUB_URL="https://github.com/danielbrendel/hortusfox-web"
APP_SERVICE_URL="https://www.hortusfox.com"
APP_ENABLEHISTORY="true"
APP_HISTORY_NAME="History"
APP_ENABLE_PHOTO_SHARE="true"
`

**Comment by danielbrendel** [comment]
Most of these settings you quoted are now obtained from the database, so they do not have any effect from the .env file.

Does it work if you don't alter anything at all? Basically you can just pull and launch the docker containers and then login and change everything in the admin settings. 

Be sure to clone/download the latest version (2.0 as of now).

**Comment by gonsalvesc** [comment]
I cleared everything and started from scratch. It works now! Only change I had to make on the docker compose file was to use Mariadb 10.11. For some reason version 11 would not connect.

**Comment by danielbrendel** [comment]
Resolved.

**Comment by zmweske** [comment]
I find I get the same deprecated message when creating an APP_WORKSPACE with a apostrophe: "Jenny's Plants" vs "House Plants"

**Comment by zmweske** [comment]
I tried escaping the single quote by doing "Jenny''s Plants" but it created a fatal error instead of fixing anything

**Comment by zmweske** [comment]
I was able to fix it by deleting the database and setting the env variable to `"Jenny''s Plants"` such that the apostrophe is represented by _2 single (') quotes_
