### ISSUE TITLE
[Feature request] Add plant database

### ISSUE THREAD

**Issue by InputObject2** [danielbrendel/hortusfox-web#97]
Have a sort of plant "database" where a user can select via search the type of plant when adding one. 

For example, if I'm planting "blueberries" i'd like to be able to pick it from a list. 

This would be a separate field from the 'name'.

The idea behind this is that it would be a first step towards adding a community-maintained database of plants and best practices that could tie in with cronjobs and give tips about soil composition and watering amounts.

**Comment by sunjam** [comment]
Perhaps Plantbook would be the way to go for automating identification

https://plantbook.io/developers/

**Comment by danielbrendel** [comment]
That sounds very interesting! 

If we'd choose a community based plant info database then we could use the hortusfox.com homepage or, as @sunjam suggested, a third party service.

The former would require extra work and strong participation I guess. The latter one would be easier. I'll check out plantbook and other services and then compare them.

**Comment by nykroy** [comment]
You could use http://trefle.io/ and the users only need to add their token on profile page of the application

**Comment by danielbrendel** [comment]
> You could use http://trefle.io/ and the users only need to add their token on profile page of the application

As of my recent knowledge according to a Twitter post, Trefle did shut down their service, didn't they?

**Comment by nykroy** [comment]
I use trefle with plant-it without problem

**Comment by sunjam** [comment]
Seems trefle changed sponsors, but is back in full swing according to https://trefle.io/
- [API Info](https://docs.trefle.io/reference/
- [Trefle API Github repo](https://github.com/treflehq/trefle-api), coded in Rust.
- [Getting Started documentation](https://docs.trefle.io/docs/guides/getting-started)

**Comment by ThomasLewis1028** [comment]
My suggestion, as someone with a wife who loves plants and me being a big self-hoster, would be to add a setting where I could add my API key, or maybe bake it into the docker file and then whichever tool I use, I can have my own account and have it pull the data. I don't mind storing it locally as well, so as long as something like trefle or plantbook don't update the information after the fact much, then I can grab those on plant creation and just leave it local.

If those APIs do update, then maybe have a setting to try and grab more information at a given interval, so I could do mine every night or once a week. 

These are just my two-cents, I'd love a tool like this to replace some monthly payments on my wife's part, and it's always fun to set things up!

**Comment by danielbrendel** [comment]
Seems Trefle is abandoned.

- Sign up doesn't work, so I can't get an API key (I tried it multiple times)
- Issues are not answered
- Last commit is about two years ago

If anyone knows an alternative, please let me know. But for now this issue is postponed.

**Comment by RJSkudra** [comment]
https://perenual.com/plant-database-search-guide this seems to have some usable data and an API.
https://garden.org/thread/view/59962/Database-APIs/ maybe the owner of this website can be persuaded to sponsor HortusFox with data. His e-mail is in the linked forum thread.

**Comment by KalyaSc** [comment]
There's also plantnet:
https://github.com/plantnet

Also Trefle on their website:
```
Trefle is coming back !
Trefle is currently being restored, and is now backed by [Mashum](https://mashum.org/)
```

**Comment by RJSkudra** [comment]
@KalyaSc Trefle seems to not be so active anymore. Your quoted text has been on the website since after they repurchased/paid for the domain in March 2023 (https://web.archive.org/web/20230323143127/http://trefle.io/). Their repo also seems to not have any action for a few years, but I was able to get their API token.

**Comment by danielbrendel** [comment]
I'm closing this now, since it seems there won't be any comparable service in the forseeable future. If that ever changes, I'll gladly re-open this issue.
